### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by Sidbaba** [shauryauppal/PyWhatsapp#10] opened 2018-09-09 16:09 UTC
File "PyWhatsapp.py", line 47, in whatsapp_login
    browser.maximize_window()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 736, in maximize_window
    self.execute(command, params)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=68.0.3440.106)

**Comment by Sidbaba** [comment] 2018-09-09 16:46
Worked well how can I send msg to a number without saving ?

**Comment by shauryauppal** [comment] 2018-09-09 16:52
Thanks a lot for raising this point, that will be my next task now. Will soon implement that. Till now that is not implemented. 

@Sidbaba 👍 

Sorry for now you have to save that number and that number should be in your recent chats section.

Not in all contacts section.

**Comment by shauryauppal** [comment] 2018-09-09 16:53
I surely come up with, without saving contact add-on in a week or two. Currently a bit busy with work.

I hope the reason for with the issue is raised is solved. Closing the Issue.

**Closed** 2018-09-09 16:54 UTC

**Comment by Sidbaba** [comment] 2018-09-09 16:55
Your welcome buddy , I m also working on kinda same thing plz check
api.whatsapp.com/?phone=number&msg= something like this using this we can
open unknown number in chat window and all we need to automate click button
, not sure will work just a thought anyways awesome code you have written
Thanks

**Comment by shauryauppal** [comment] 2018-09-09 16:57
https://www.timesnownews.com/technology-science/article/whatsapp-how-to-start-a-whatsapp-chat-without-saving-number-on-your-smartphone/281632

Yes, I read that article yesterday on news.

**Comment by shauryauppal** [comment] 2018-09-09 17:00
Just a matter of few more lines will surely come up with this before next Sunday.

**Comment by Sidbaba** [comment] 2018-09-09 17:01
Cool bro ....

**Comment by Sidbaba** [comment] 2018-09-09 18:07
BTW I have modified your code and implemented that functionality only
problem is that send button click is not working it's opening the number
with perpopulated msg in web.whatsapp window but not clicking the send
button

**Comment by shauryauppal** [comment] 2018-09-16 11:32
@Sidbaba 
Issue resolved Feature added. 👍 

Now you can send messages to unsaved contacts also.

**Comment by Sidbaba** [comment] 2018-09-18 05:10
Awesome
