### ISSUE TITLE
Add contacts contacts in bulk

### ISSUE THREAD

**Issue by pengyanbing84** [shauryauppal/PyWhatsapp#34] opened 2019-08-12 03:08 UTC
How do I add contacts contacts in bulk?

**Comment by shauryauppal** [comment] 2019-08-13 15:38
Add lot of contacts in the send list and after a batch (max. 4) msg add a time sleep with a random value. It should look human else whatsapp will ban you.

**Comment by shauryauppal** [comment] 2019-10-02 22:38
Duplicate of #31

**Closed** 2019-11-02 19:54 UTC
Labels: duplicate, enhancement, good first issue, hacktoberfest

**Comment by Abhi-jeet1** [comment] 2020-02-08 14:49
it is not sending a message to more than one unsaved contact..so can you take look on it
